### ISSUE TITLE
hot-reload is not correctly re-executing RunScript

### ISSUE THREAD

**Issue by amoshydra** [amoshydra/tasker-js-runner#1]

**Comment by danielo515** [comment]
Hey!
Nice project.
What do you mean by not correctly re-executing? If you mean that it does not download the newest version of the script I think it is because tasker is caching all the responses from network requests, which includes the fetch your update script does. 
I've been doing some tests and after cleaning tasker cache it then downloads properly the latest version of my script. 
This happens also to scriptlets libraries. Seems that tasker downloads them once and never again.

**Comment by amoshydra** [comment]
Hi Denielo

This issue has been fixed in 0.1.3 with https://github.com/amoshydra/tasker-js-runner/commit/fc6fe4feaba3bb44c7d051fb5387399b3e62b6a5

During my usage, the script got downloaded correctly. The issue with "not correctly re-executing" come from the code below, where the task `'TJS:RunScript'` is getting re-executed programatically. 

https://github.com/amoshydra/tasker-js-runner/blob/fc6fe4feaba3bb44c7d051fb5387399b3e62b6a5/src/index.js#L17-L21

`'TJS:RunScript'` rely on a tasker provided local variable `caller1` to determine which profile called the task. When `'TJS:RunScript'` get re-executed, `caller1` will no longer be the profile the called the task. Instead, it will be stored inside `caller2`.

Before fc6fe4fe, `'TJS:RunScript'` only accessed `caller1`, therefore the script failed to get re-executed.

##### Side note
During my usage I have not encountered any caching issue with the Fetch call. However if it is a problem for you, perhaps we can add an additional cache header in the Fetch call to disable caching https://developer.mozilla.org/en-US/docs/Web/API/Request/cache
